In [4]:
import numpy as np
import pandas as pd
df = pd.read_csv("movies_2.csv")
df

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary
0,1,Look Who's Talking,PG-13,7500000.0,2.960000e+08,1989-10-12,Romance,93.0,5.9,73638.0,"After a single, career-minded woman is left on..."
1,2,Driving Miss Daisy,PG,7500000.0,1.457933e+08,1989-12-13,Comedy,99.0,7.4,91075.0,An old Jewish woman and her African-American c...
2,3,Turner & Hooch,PG,13000000.0,7.107992e+07,1989-07-28,Crime,100.0,7.2,91415.0,"Det. Scott Turner (Tom Hanks) is an uptight, b..."
3,4,Born on the Fourth of July,R,14000000.0,1.610017e+08,1989-12-20,War,145.0,7.2,91415.0,The biography of Ron Kovic. Paralyzed in the V...
4,5,Field of Dreams,PG,15000000.0,8.443162e+07,1989-04-21,Drama,107.0,7.5,101702.0,"An Iowa corn farmer, hearing voices, interpret..."
...,...,...,...,...,...,...,...,...,...,...,...
611,612,Toy Story 4,G,200000000.0,1.062000e+09,2019-06-11,Animation,100.0,NaN,NaN,NaN
612,613,Fast & Furious Presents: Hobbs & Shaw,PG-13,200000000.0,7.594000e+08,2019-07-13,Thriller,136.0,NaN,NaN,NaN
613,614,The Lion King,PG,250000000.0,1.632000e+09,2019-07-09,Drama,118.0,NaN,NaN,NaN
614,615,Avengers: Endgame,PG-13,356000000.0,2.796000e+09,2019-04-22,Action,181.0,NaN,NaN,NaN
615,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# df.head(5)
print(df.shape)

(616, 11)

In [6]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 616 entries, 0 to 615
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   MovieID       616 non-null    int64
 1   Title         615 non-null    object
 2   MPAA Rating   615 non-null    object
 3   Budget        615 non-null    float64
 4   Gross         615 non-null    float64
 5   Release Date  615 non-null    object
 6   Genre         615 non-null    object
 7   Runtime       615 non-null    float64
 8   Rating        508 non-null    float64
 9   Rating Count  508 non-null    float64
 10  Summary       496 non-null    object
dtypes: float64(5), int64(1), object(5)
memory usage: 53.1+ KB
None

In [7]:
print(df.dtypes)

MovieID           int64
Title            object
MPAA Rating      object
Budget          float64
Gross           float64
Release Date     object
Genre            object
Runtime         float64
Rating          float64
Rating Count    float64
Summary          object
dtype: object

In [8]:
print(df.isna().sum())

MovieID           0
Title             1
MPAA Rating       1
Budget            1
Gross             1
Release Date      1
Genre             1
Runtime           1
Rating          108
Rating Count    108
Summary         120
dtype: int64

In [10]:
df.describe()

,MovieID,Budget,Gross,Runtime,Rating,Rating Count
count,616.000000,6.150000e+02,6.150000e+02,615.000000,508.000000,5.080000e+02
mean,307.500000,9.491710e+07,4.453221e+08,118.642276,6.917323,3.392521e+05
std,177.968162,6.748114e+07,3.394075e+08,22.252376,0.888928,3.213388e+05
min,0.000000,6.000000e+04,5.300000e+07,79.000000,4.100000,1.491800e+04
25%,153.750000,4.000000e+07,2.158939e+08,102.000000,6.400000,1.275922e+05
50%,307.500000,8.000000e+07,3.510404e+08,117.000000,6.900000,2.403475e+05
75%,461.250000,1.400000e+08,5.851766e+08,132.000000,7.600000,4.257000e+05
max,615.000000,4.000000e+08,2.796000e+09,201.000000,9.000000,2.127228e+06

In [11]:
print('null values', df.isna().any())

null values MovieID         False
Title            True
MPAA Rating      True
Budget           True
Gross            True
Release Date     True
Genre            True
Runtime          True
Rating           True
Rating Count     True
Summary          True
dtype: bool

In [13]:
df.drop("Summary", axis = 1)

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count
0,1,Look Who's Talking,PG-13,7500000.0,2.960000e+08,1989-10-12,Romance,93.0,5.9,73638.0
1,2,Driving Miss Daisy,PG,7500000.0,1.457933e+08,1989-12-13,Comedy,99.0,7.4,91075.0
2,3,Turner & Hooch,PG,13000000.0,7.107992e+07,1989-07-28,Crime,100.0,7.2,91415.0
3,4,Born on the Fourth of July,R,14000000.0,1.610017e+08,1989-12-20,War,145.0,7.2,91415.0
4,5,Field of Dreams,PG,15000000.0,8.443162e+07,1989-04-21,Drama,107.0,7.5,101702.0
...,...,...,...,...,...,...,...,...,...,...
611,612,Toy Story 4,G,200000000.0,1.062000e+09,2019-06-11,Animation,100.0,NaN,NaN
612,613,Fast & Furious Presents: Hobbs & Shaw,PG-13,200000000.0,7.594000e+08,2019-07-13,Thriller,136.0,NaN,NaN
613,614,The Lion King,PG,250000000.0,1.632000e+09,2019-07-09,Drama,118.0,NaN,NaN
614,615,Avengers: Endgame,PG-13,356000000.0,2.796000e+09,2019-04-22,Action,181.0,NaN,NaN
615,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
df[['Gross', 'Budget']].mean()

Gross     4.453221e+08
Budget    9.491710e+07
dtype: float64

In [26]:
# df.astype({"Budget":integer,"Gross":integer})

In [25]:
# df['Release_date']= pd.to_datetime(df["Release_date"])
#     df.dtypes

In [19]:
# use the fillna() method to replace the missing values of Rating with their median
df.fillna(df["Rating"].median())

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary
0,1,Look Who's Talking,PG-13,7500000.0,2.960000e+08,1989-10-12,Romance,93.0,5.9,73638.0,"After a single, career-minded woman is left on..."
1,2,Driving Miss Daisy,PG,7500000.0,1.457933e+08,1989-12-13,Comedy,99.0,7.4,91075.0,An old Jewish woman and her African-American c...
2,3,Turner & Hooch,PG,13000000.0,7.107992e+07,1989-07-28,Crime,100.0,7.2,91415.0,"Det. Scott Turner (Tom Hanks) is an uptight, b..."
3,4,Born on the Fourth of July,R,14000000.0,1.610017e+08,1989-12-20,War,145.0,7.2,91415.0,The biography of Ron Kovic. Paralyzed in the V...
4,5,Field of Dreams,PG,15000000.0,8.443162e+07,1989-04-21,Drama,107.0,7.5,101702.0,"An Iowa corn farmer, hearing voices, interpret..."
...,...,...,...,...,...,...,...,...,...,...,...
611,612,Toy Story 4,G,200000000.0,1.062000e+09,2019-06-11,Animation,100.0,6.9,6.9,6.9
612,613,Fast & Furious Presents: Hobbs & Shaw,PG-13,200000000.0,7.594000e+08,2019-07-13,Thriller,136.0,6.9,6.9,6.9
613,614,The Lion King,PG,250000000.0,1.632000e+09,2019-07-09,Drama,118.0,6.9,6.9,6.9
614,615,Avengers: Endgame,PG-13,356000000.0,2.796000e+09,2019-04-22,Action,181.0,6.9,6.9,6.9
615,0,6.9,6.9,6.9,6.900000e+00,6.9,6.9,6.9,6.9,6.9,6.9

In [20]:
# Drop the duplicates, if any
df.drop_duplicates()

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary
0,1,Look Who's Talking,PG-13,7500000.0,2.960000e+08,1989-10-12,Romance,93.0,5.9,73638.0,"After a single, career-minded woman is left on..."
1,2,Driving Miss Daisy,PG,7500000.0,1.457933e+08,1989-12-13,Comedy,99.0,7.4,91075.0,An old Jewish woman and her African-American c...
2,3,Turner & Hooch,PG,13000000.0,7.107992e+07,1989-07-28,Crime,100.0,7.2,91415.0,"Det. Scott Turner (Tom Hanks) is an uptight, b..."
3,4,Born on the Fourth of July,R,14000000.0,1.610017e+08,1989-12-20,War,145.0,7.2,91415.0,The biography of Ron Kovic. Paralyzed in the V...
4,5,Field of Dreams,PG,15000000.0,8.443162e+07,1989-04-21,Drama,107.0,7.5,101702.0,"An Iowa corn farmer, hearing voices, interpret..."
...,...,...,...,...,...,...,...,...,...,...,...
611,612,Toy Story 4,G,200000000.0,1.062000e+09,2019-06-11,Animation,100.0,NaN,NaN,NaN
612,613,Fast & Furious Presents: Hobbs & Shaw,PG-13,200000000.0,7.594000e+08,2019-07-13,Thriller,136.0,NaN,NaN,NaN
613,614,The Lion King,PG,250000000.0,1.632000e+09,2019-07-09,Drama,118.0,NaN,NaN,NaN
614,615,Avengers: Endgame,PG-13,356000000.0,2.796000e+09,2019-04-22,Action,181.0,NaN,NaN,NaN
615,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
# importing pandas as pd
import pandas as pd
# Making data frame from the csv file
df = pd.read_csv("movies_2.csv")
df[:10]

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary
0,1,Look Who's Talking,PG-13,7500000.0,296000000.0,1989-10-12,Romance,93.0,5.9,73638.0,"After a single, career-minded woman is left on..."
1,2,Driving Miss Daisy,PG,7500000.0,145793296.0,1989-12-13,Comedy,99.0,7.4,91075.0,An old Jewish woman and her African-American c...
2,3,Turner & Hooch,PG,13000000.0,71079915.0,1989-07-28,Crime,100.0,7.2,91415.0,"Det. Scott Turner (Tom Hanks) is an uptight, b..."
3,4,Born on the Fourth of July,R,14000000.0,161001698.0,1989-12-20,War,145.0,7.2,91415.0,The biography of Ron Kovic. Paralyzed in the V...
4,5,Field of Dreams,PG,15000000.0,84431625.0,1989-04-21,Drama,107.0,7.5,101702.0,"An Iowa corn farmer, hearing voices, interpret..."
5,6,Uncle Buck,PG,15000000.0,79258538.0,1989-08-16,Family,100.0,7.0,77659.0,Bachelor and all-round slob Buck babysits his ...
6,7,When Harry Met Sally...,R,16000000.0,92800000.0,1989-07-21,Romance,96.0,7.6,180871.0,Harry and Sally have known each other for year...
7,8,Dead Poets Society,PG,16400000.0,235860116.0,1989-06-02,Drama,129.0,8.1,382002.0,English teacher John Keating inspires his stud...
8,9,Parenthood,PG-13,20000000.0,126297830.0,1989-07-31,Comedy,124.0,7.0,41866.0,The Buckmans are a midwestern family all deali...
9,10,Lethal Weapon 2,R,25000000.0,227853986.0,1989-07-07,Comedy,114.0,7.2,151737.0,Riggs and Murtaugh are on the trail of South A...

In [27]:
# 1.show the movies with more than 7 in Rating & greater than 50 million Gross

df[(df['Rating'] > 7) & (df["Gross"] > 50000000)]

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary
1,2,Driving Miss Daisy,PG,7500000.0,145793296.0,1989-12-13,Comedy,99.0,7.4,91075.0,An old Jewish woman and her African-American c...
2,3,Turner & Hooch,PG,13000000.0,71079915.0,1989-07-28,Crime,100.0,7.2,91415.0,"Det. Scott Turner (Tom Hanks) is an uptight, b..."
3,4,Born on the Fourth of July,R,14000000.0,161001698.0,1989-12-20,War,145.0,7.2,91415.0,The biography of Ron Kovic. Paralyzed in the V...
4,5,Field of Dreams,PG,15000000.0,84431625.0,1989-04-21,Drama,107.0,7.5,101702.0,"An Iowa corn farmer, hearing voices, interpret..."
6,7,When Harry Met Sally...,R,16000000.0,92800000.0,1989-07-21,Romance,96.0,7.6,180871.0,Harry and Sally have known each other for year...
...,...,...,...,...,...,...,...,...,...,...,...
505,506,Big Hero 6,PG,165000000.0,652105443.0,2014-10-24,Animation,102.0,7.8,380953.0,The special bond that develops between plus-si...
506,507,Interstellar,PG-13,165000000.0,675120017.0,2014-11-05,Science Fiction,169.0,8.6,1343549.0,A team of explorers travel through a wormhole ...
507,508,Captain America: The Winter Soldier,PG-13,170000000.0,714766572.0,2014-03-20,Action,136.0,7.7,685903.0,As Steve Rogers struggles to embrace his role ...
508,509,Dawn of the Planet of the Apes,PG-13,170000000.0,710644566.0,2014-06-26,Science Fiction,130.0,7.6,395425.0,A growing nation of genetically evolved apes l...
509,510,Guardians of the Galaxy,PG-13,170000000.0,773328629.0,2014-07-30,Action,121.0,8.0,978222.0,A group of intergalactic criminals must pull t...

In [32]:
# 2.show the movies with more than 7 in Rating & greater than 50 million Gross & with Parental guidance as MPAA Rating

df = df[(df['Rating'] > 7) & (df['Gross'] >  50000000) & (df['MPAA Rating'] == 'PG')]
print(df)

     MovieID                                     Title MPAA Rating  \
1          2                        Driving Miss Daisy          PG
2          3                            Turner & Hooch          PG
4          5                           Field of Dreams          PG
7          8                        Dead Poets Society          PG
13        14                                    Batman          PG
15        16                        The Little Mermaid          PG
16        17                Back to the Future Part II          PG
19        20                           Steel Magnolias          PG
24        25                                Home Alone          PG
32        33                  The Hunt for Red October          PG
34        35               Back to the Future Part III          PG
45        46           Teenage Mutant Ninja Turtles II          PG
46        47                      Beauty and the Beast          PG
49        50    Star Trek VI: The Undiscovered Country          PG
72        73                     A League of Their Own          PG
80        81                             Groundhog Day          PG
106      107                    Star Trek: Generations          PG
126      127                        Mr. Holland's Opus          PG
130      131                                 Apollo 13          PG
174      175                                   Contact          PG
185      186                           The Truman Show          PG
188      189                       The Prince of Egypt          PG
215      216                                    Tarzan          PG
220      221                       Remember the Titans          PG
241      242                                     Shrek          PG
255      256     Harry Potter and the Sorcerer's Stone          PG
261      262                                   Ice Age          PG
270      271   Harry Potter and the Chamber of Secrets          PG
304      305                           The Incredibles          PG
309      310  Harry Potter and the Prisoner of Azkaban          PG
311      312                                   Shrek 2          PG
385      386                             Kung Fu Panda          PG
410      411                        Monsters vs Aliens          PG
411      412                                        Up          PG
415      416    Harry Potter and the Half-Blood Prince          PG
420      421                             Despicable Me          PG
425      426                                  Megamind          PG
428      429                  How to Train Your Dragon          PG
435      436                                   Tangled          PG
447      448          Puss in Boots: The Three Diablos          PG
451      452                           Kung Fu Panda 2          PG
461      462                        Hotel Transylvania          PG
466      467                            Wreck-It Ralph          PG
468      469                                     Brave          PG
480      481                           Despicable Me 2          PG
484      485                                The Croods          PG
485      486                                    Frozen          PG
498      499                            The Lego Movie          PG
503      504                How to Train Your Dragon 2          PG
505      506                                Big Hero 6          PG

          Budget         Gross Release Date            Genre  Runtime  Rating  \
1      7500000.0  1.457933e+08   1989-12-13           Comedy     99.0     7.4
2     13000000.0  7.107992e+07   1989-07-28            Crime    100.0     7.2
4     15000000.0  8.443162e+07   1989-04-21            Drama    107.0     7.5
7     16400000.0  2.358601e+08   1989-06-02            Drama    129.0     8.1
13    35000000.0  4.113489e+08   1989-06-23           Action    126.0     7.5
15    40000000.0  2.223000e+08   1989-11-17        Animation     83.0     7.6
16    40000000.0  3.320000e+08   1989-11-20  Science Fiction    108.0     7.8
19    15000000.0  9.590409e+07   1989-11-15            Drama    119.0     7.3
24    18000000.0  4.766847e+08   1990-11-09           Family    103.0     7.6
32    30000000.0  1.992000e+08   1990-03-02         Thriller    134.0     7.6
34    40000000.0  2.445276e+08   1990-05-25           Family    118.0     7.4
45    25000000.0  7.860000e+07   1991-03-22           Action     88.0     8.0
46    25000000.0  3.773506e+08   1991-11-13        Animation     84.0     8.0
49    27000000.0  9.690000e+07   1991-12-05  Science Fiction    113.0     7.2
72    40000000.0  1.074588e+08   1992-07-01           Comedy    128.0     7.2
80    14600000.0  7.090697e+07   1993-02-11           Comedy    101.0     8.0
106   38000000.0  1.200000e+08   1994-11-17  Science Fiction    118.0     8.5
126   31000000.0  1.062700e+08   1995-12-29           Family    137.0     7.3
130   52000000.0  3.552379e+08   1995-06-30            Drama    140.0     7.6
174   90000000.0  1.711203e+08   1997-07-11  Science Fiction    150.0     7.4
185   60000000.0  2.641182e+08   1998-06-04           Comedy    103.0     8.1
188   70000000.0  2.186132e+08   1998-12-15        Animation     99.0     7.1
215  150000000.0  4.480000e+08   1999-06-18        Animation     88.0     7.3
220   30000000.0  1.367067e+08   2000-09-29            Drama    113.0     7.8
241   60000000.0  4.844092e+08   2001-05-16        Animation     90.0     7.8
255  125000000.0  9.751000e+08   2001-11-04          Fantasy    152.0     7.6
261   59000000.0  3.832571e+08   2002-03-10        Animation     81.0     7.5
270  100000000.0  8.766885e+08   2002-11-13          Fantasy    161.0     7.4
304   92000000.0  6.314421e+08   2004-11-05        Animation    115.0     8.0
309  130000000.0  7.898046e+08   2004-05-31          Fantasy    141.0     7.9
311  150000000.0  9.198388e+08   2004-05-19        Animation     93.0     7.2
385  130000000.0  6.317446e+08   2008-06-04        Animation     90.0     7.5
410  175000000.0  3.815099e+08   2009-03-19        Animation     94.0     7.7
411  175000000.0  7.350991e+08   2009-05-13        Animation     96.0     8.2
415  250000000.0  9.339592e+08   2009-07-07          Fantasy    153.0     7.6
420   69000000.0  5.435140e+08   2010-07-08        Animation     95.0     7.6
425  130000000.0  3.218872e+08   2010-10-28        Animation     95.0     7.2
428  165000000.0  4.948788e+08   2010-03-05        Animation     98.0     8.1
435  260000000.0  5.917949e+08   2010-11-24        Animation    100.0     7.7
447  130000000.0  5.550000e+08   2011-12-08        Animation    130.0     7.8
451  150000000.0  6.656923e+08   2011-05-25        Animation     91.0     7.2
461   85000000.0  3.583756e+08   2012-09-20        Animation     91.0     7.1
466  165000000.0  4.712229e+08   2012-11-01        Animation    108.0     7.7
468  185000000.0  5.389832e+08   2012-06-21        Animation     93.0     7.1
480   76000000.0  9.707619e+08   2013-06-25        Animation     98.0     7.4
484  135000000.0  5.851789e+08   2013-03-20        Animation     98.0     7.2
485  150000000.0  1.274219e+09   2013-11-27        Animation    102.0     7.5
498   60000000.0  4.691607e+08   2014-02-06        Animation    100.0     7.8
503  145000000.0  6.091230e+08   2014-06-12        Animation    102.0     7.8
505  165000000.0  6.521054e+08   2014-10-24        Animation    102.0     7.8

     Rating Count                                            Summary
1         91075.0  An old Jewish woman and her African-American c...
2         91415.0  Det. Scott Turner (Tom Hanks) is an uptight, b...
4        101702.0  An Iowa corn farmer, hearing voices, interpret...
7        382002.0  English teacher John Keating inspires his stud...
13       319517.0  The Dark Knight of Gotham City begins his war ...
15       219221.0  A mermaid princess makes a Faustian bargain in...
16       438940.0  After visiting 2015, Marty McFly must repeat h...
19        43037.0  A young beautician, newly arrived in a small L...
24       414472.0  An eight-year-old troublemaker must protect hi...
32       167212.0  In November 1984, the Soviet Unions best subma...
34       369652.0  Learning about the death of Doc Brown in 1885,...
45       397467.0  The Turtles and the Shredder battle once again...
46       397467.0  A prince cursed to spend his days as a hideous...
49        66086.0  On the eve of retirement, Kirk and McCoy are c...
72        85932.0  Two sisters join the first female professional...
80       549538.0  A weatherman finds himself inexplicably living...
106      869127.0  With the help of long presumed dead Captain Ki...
126       33906.0  A frustrated composer finds fulfillment as a h...
130      250975.0  NASA must devise a strategy to return Apollo 1...
174      239569.0  Dr. Ellie Arroway (Jodie Foster), after years ...
185      859224.0  An insurance salesman discovers his whole life...
188      110340.0  An Egyptian prince learns of his identity as a...
215      187724.0  A man raised by gorillas must decide where he ...
220      186997.0  The true story of a newly appointed African-Am...
241      574978.0  A mean lord exiles fairytale creatures to the ...
255      583224.0  An orphaned boy enrolls in a school of wizardr...
261      411963.0  Set during the Ice Age, a sabertooth tiger, a ...
270      505027.0  An ancient prophecy seems to be coming true wh...
304      617102.0  A family of undercover superheroes, while tryi...
309      501648.0  Its Harrys third year at Hogwarts; not only do...
311      391295.0  Princess Fionas parents invite her and Shrek t...
385      390478.0  The Dragon Warrior has to clash against the sa...
410      374981.0                                                NaN
411      867393.0  Seventy-eight year old Carl Fredricksen travel...
415      429384.0  As Harry Potter begins his sixth year at Hogwa...
420      473121.0  When a criminal mastermind uses a trio of orph...
425      212563.0  The supervillain Megamind finally defeats his ...
428      624128.0  A hapless young Viking who aspires to hunt dra...
435      374981.0  The magically long-haired Rapunzel has spent h...
447      727724.0                                                NaN
451      234612.0  Po and his friends fight to stop a peacock vil...
461      208916.0  Dracula, who operates a high-end resort away f...
466      354202.0  A video game villain wants to be a hero and se...
468      346490.0  Determined to make her own path in life, Princ...
480      350582.0  When Gru, the worlds most super-bad turned sup...
484      180043.0  After their cave is destroyed, a caveman famil...
485      527284.0  When the newly-crowned Queen Elsa accidentally...
498      309295.0  An ordinary LEGO construction worker, thought ...
503      285394.0  When Hiccup and Toothless discover an ice cave...
505      380953.0  The special bond that develops between plus-si...

In [34]:
# 3.show the count of Animation movies with more than 7 in Rating (use the shape() method)
df[(df['Genre'] == 'Animation') & (df["Rating"] > 7)].shape

(26, 11)

In [35]:
# 4.show the top 5 movies based on Budget

df.sort_values("Budget", ascending=False).head(5)

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary
435,436,Tangled,PG,260000000.0,591794936.0,2010-11-24,Animation,100.0,7.7,374981.0,The magically long-haired Rapunzel has spent h...
415,416,Harry Potter and the Half-Blood Prince,PG,250000000.0,933959197.0,2009-07-07,Fantasy,153.0,7.6,429384.0,As Harry Potter begins his sixth year at Hogwa...
468,469,Brave,PG,185000000.0,538983207.0,2012-06-21,Animation,93.0,7.1,346490.0,"Determined to make her own path in life, Princ..."
410,411,Monsters vs Aliens,PG,175000000.0,381509870.0,2009-03-19,Animation,94.0,7.7,374981.0,NaN
411,412,Up,PG,175000000.0,735099082.0,2009-05-13,Animation,96.0,8.2,867393.0,Seventy-eight year old Carl Fredricksen travel...

In [36]:
# 5.show the top 5 Comedy movies by Rating

df[df['Genre'] == "Comedy"]
df[df['Genre'] == "Comedy"].sort_values("Rating", ascending=False).head(5)

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary
185,186,The Truman Show,PG,60000000.0,264118201.0,1998-06-04,Comedy,103.0,8.1,859224.0,An insurance salesman discovers his whole life...
80,81,Groundhog Day,PG,14600000.0,70906973.0,1993-02-11,Comedy,101.0,8.0,549538.0,A weatherman finds himself inexplicably living...
1,2,Driving Miss Daisy,PG,7500000.0,145793296.0,1989-12-13,Comedy,99.0,7.4,91075.0,An old Jewish woman and her African-American c...
72,73,A League of Their Own,PG,40000000.0,107458785.0,1992-07-01,Comedy,128.0,7.2,85932.0,Two sisters join the first female professional...

In [37]:
# 6.top 5 movie names by Rating

df.sort_values("Rating", ascending=False).head(5)

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary
106,107,Star Trek: Generations,PG,38000000.0,120000000.0,1994-11-17,Science Fiction,118.0,8.5,869127.0,With the help of long presumed dead Captain Ki...
411,412,Up,PG,175000000.0,735099082.0,2009-05-13,Animation,96.0,8.2,867393.0,Seventy-eight year old Carl Fredricksen travel...
185,186,The Truman Show,PG,60000000.0,264118201.0,1998-06-04,Comedy,103.0,8.1,859224.0,An insurance salesman discovers his whole life...
7,8,Dead Poets Society,PG,16400000.0,235860116.0,1989-06-02,Drama,129.0,8.1,382002.0,English teacher John Keating inspires his stud...
428,429,How to Train Your Dragon,PG,165000000.0,494878759.0,2010-03-05,Animation,98.0,8.1,624128.0,A hapless young Viking who aspires to hunt dra...

In [103]:
# 7.top 3 high Gross Romance movies released after 1999 (typecast it to datetime)

from datetime import datetime
# df[(df['Genre'] == "Romance") & (df["Release_Date"] > datetime.strptime("1999-12-31", "%Y-%m-%d"))].sort_values("Gross", ascending=False).head(3)

In [39]:
# 8.how many Genres are present in the dataframe? (use value_counts() method which applies to Series, not Dataframe)
Genre_series  = df['Genre'].explode()
Genre_series.value_counts()

Genre
Animation          26
Drama               5
Comedy              4
Science Fiction     4
Fantasy             4
Family              3
Action              2
Crime               1
Thriller            1
Name: count, dtype: int64

In [ ]:
# 9.top 5 most expensive movies released after 1999 (measured by Budget)
df[df["Release Date"], datetime.strptime(1999-12-31, %y-%m-%d)]
df.sort_values("Budget",ascending = False).head(5)

SyntaxError: invalid syntax (1641664054.py, line 2)

In [66]:
# 10.most & least frequent MPAA Rating in the dataset in terms of occurrences
mpaa_rating_counts = df['MPAA Rating'].value_counts()
print("Most freq MPAA Rating :", Rating_series.max())
print("Less freq MPAA Rating :",Rating_series.min())

Most freq MPAA Rating : PG
Less freq MPAA Rating : PG

In [43]:
# 11.most & least expensive Genre (take an average of all Budget measures grouped by Genre - use the groupBy() method)

Budget_avg_Genre = df.groupby('Genre')["Budget"].mean()
Budget_avg_Genre

Genre
Action             3.000000e+07
Animation          1.229231e+08
Comedy             3.052500e+07
Crime              1.300000e+07
Drama              2.568000e+07
Family             2.966667e+07
Fantasy            1.512500e+08
Science Fiction    4.875000e+07
Thriller           3.000000e+07
Name: Budget, dtype: float64

In [68]:
# 12.which Genre is favoured the most?
most_rating_count = df.groupby('Genre')['Rating Count'].value_counts()
most_rating_count.head(1)

Genre   Rating Count
Action  319517.0        1
Name: count, dtype: int64