In [1]:
#importing pandas as pd
import pandas as pd

In [55]:
df = pd.read_csv('./movies_2.csv')
df

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary
0,1,Look Who's Talking,PG-13,7500000.0,2.960000e+08,1989-10-12,Romance,93.0,5.9,73638.0,"After a single, career-minded woman is left on..."
1,2,Driving Miss Daisy,PG,7500000.0,1.457933e+08,1989-12-13,Comedy,99.0,7.4,91075.0,An old Jewish woman and her African-American c...
2,3,Turner & Hooch,PG,13000000.0,7.107992e+07,1989-07-28,Crime,100.0,7.2,91415.0,"Det. Scott Turner (Tom Hanks) is an uptight, b..."
3,4,Born on the Fourth of July,R,14000000.0,1.610017e+08,1989-12-20,War,145.0,7.2,91415.0,The biography of Ron Kovic. Paralyzed in the V...
4,5,Field of Dreams,PG,15000000.0,8.443162e+07,1989-04-21,Drama,107.0,7.5,101702.0,"An Iowa corn farmer, hearing voices, interpret..."
...,...,...,...,...,...,...,...,...,...,...,...
611,612,Toy Story 4,G,200000000.0,1.062000e+09,2019-06-11,Animation,100.0,NaN,NaN,NaN
612,613,Fast & Furious Presents: Hobbs & Shaw,PG-13,200000000.0,7.594000e+08,2019-07-13,Thriller,136.0,NaN,NaN,NaN
613,614,The Lion King,PG,250000000.0,1.632000e+09,2019-07-09,Drama,118.0,NaN,NaN,NaN
614,615,Avengers: Endgame,PG-13,356000000.0,2.796000e+09,2019-04-22,Action,181.0,NaN,NaN,NaN
615,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [56]:
#the number of rows and columns present in the data set (i.e. the shape of the dataframe)
df.shape

(616, 11)

In [57]:
#columns present in the data set, along with the data type (use info or dtypes method)
df.info

<bound method DataFrame.info of      MovieID                                  Title MPAA Rating       Budget  \
0          1                     Look Who's Talking       PG-13    7500000.0
1          2                     Driving Miss Daisy          PG    7500000.0
2          3                         Turner & Hooch          PG   13000000.0
3          4             Born on the Fourth of July           R   14000000.0
4          5                        Field of Dreams          PG   15000000.0
..       ...                                    ...         ...          ...
611      612                            Toy Story 4           G  200000000.0
612      613  Fast & Furious Presents: Hobbs & Shaw       PG-13  200000000.0
613      614                          The Lion King          PG  250000000.0
614      615                      Avengers: Endgame       PG-13  356000000.0
615        0                                    NaN         NaN          NaN

            Gross Release Date      Genre  Runtime  Rating  Rating Count  \
0    2.960000e+08   1989-10-12    Romance     93.0     5.9       73638.0
1    1.457933e+08   1989-12-13     Comedy     99.0     7.4       91075.0
2    7.107992e+07   1989-07-28      Crime    100.0     7.2       91415.0
3    1.610017e+08   1989-12-20        War    145.0     7.2       91415.0
4    8.443162e+07   1989-04-21      Drama    107.0     7.5      101702.0
..            ...          ...        ...      ...     ...           ...
611  1.062000e+09   2019-06-11  Animation    100.0     NaN           NaN
612  7.594000e+08   2019-07-13   Thriller    136.0     NaN           NaN
613  1.632000e+09   2019-07-09      Drama    118.0     NaN           NaN
614  2.796000e+09   2019-04-22     Action    181.0     NaN           NaN
615           NaN          NaN        NaN      NaN     NaN           NaN

                                               Summary
0    After a single, career-minded woman is left on...
1    An old Jewish woman and her African-American c...
2    Det. Scott Turner (Tom Hanks) is an uptight, b...
3    The biography of Ron Kovic. Paralyzed in the V...
4    An Iowa corn farmer, hearing voices, interpret...
..                                                 ...
611                                                NaN
612                                                NaN
613                                                NaN
614                                                NaN
615                                                NaN

[616 rows x 11 columns]>

In [58]:
#check how many NaN we have for MPAA Rating, Budget, Gross, Release Date, Genre, Runtime, 
# Rating and Rating Count columns
df.isnull().sum()

MovieID           0
Title             1
MPAA Rating       1
Budget            1
Gross             1
Release Date      1
Genre             1
Runtime           1
Rating          108
Rating Count    108
Summary         120
dtype: int64

In [ ]:
# Get rid of the Summary column (use the drop() method)
new_df = movies.drop('Summary', axis='columns') # (column = 1, row = 0)
new_df

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count
0,1,Look Who's Talking,PG-13,7500000.0,296000000.0,1989-10-12,Romance,93.0,5.9,73638.0
1,2,Driving Miss Daisy,PG,7500000.0,145793296.0,1989-12-13,Comedy,99.0,7.4,91075.0
2,3,Turner & Hooch,PG,13000000.0,71079915.0,1989-07-28,Crime,100.0,7.2,91415.0
3,4,Born on the Fourth of July,R,14000000.0,161001698.0,1989-12-20,War,145.0,7.2,91415.0
4,5,Field of Dreams,PG,15000000.0,84431625.0,1989-04-21,Drama,107.0,7.5,101702.0
...,...,...,...,...,...,...,...,...,...,...
491,506,Big Hero 6,PG,165000000.0,652105443.0,2014-10-24,Animation,102.0,7.8,380953.0
492,507,Interstellar,PG-13,165000000.0,675120017.0,2014-11-05,Science Fiction,169.0,8.6,1343549.0
493,508,Captain America: The Winter Soldier,PG-13,170000000.0,714766572.0,2014-03-20,Action,136.0,7.7,685903.0
494,509,Dawn of the Planet of the Apes,PG-13,170000000.0,710644566.0,2014-06-26,Science Fiction,130.0,7.6,395425.0
495,510,Guardians of the Galaxy,PG-13,170000000.0,773328629.0,2014-07-30,Action,121.0,8.0,978222.0

In [165]:
# use the rename method to change all columns names to lowercase, 
# and replace spaces with underscores if the name is made of more than one word
renamed = movies.rename(columns={ "MovieID": "movies", "Gross": "Profit"})
renamed.to_csv("output.csv")
renamed

,movies,Title,MPAA Rating,Budget,Profit,Release Date,Genre,Runtime,Rating,Rating Count,Summary
15,16,The Little Mermaid,PG,40000000.0,2.223000e+08,1989-11-17,Animation,83.0,7.6,219221.0,A mermaid princess makes a Faustian bargain in...
46,47,Beauty and the Beast,PG,25000000.0,3.773506e+08,1991-11-13,Animation,84.0,8.0,397467.0,A prince cursed to spend his days as a hideous...
188,189,The Prince of Egypt,PG,70000000.0,2.186132e+08,1998-12-15,Animation,99.0,7.1,110340.0,An Egyptian prince learns of his identity as a...
215,216,Tarzan,PG,150000000.0,4.480000e+08,1999-06-18,Animation,88.0,7.3,187724.0,A man raised by gorillas must decide where he ...
241,242,Shrek,PG,60000000.0,4.844092e+08,2001-05-16,Animation,90.0,7.8,574978.0,A mean lord exiles fairytale creatures to the ...
261,262,Ice Age,PG,59000000.0,3.832571e+08,2002-03-10,Animation,81.0,7.5,411963.0,"Set during the Ice Age, a sabertooth tiger, a ..."
304,305,The Incredibles,PG,92000000.0,6.314421e+08,2004-11-05,Animation,115.0,8.0,617102.0,"A family of undercover superheroes, while tryi..."
311,312,Shrek 2,PG,150000000.0,9.198388e+08,2004-05-19,Animation,93.0,7.2,391295.0,Princess Fionas parents invite her and Shrek t...
382,386,Kung Fu Panda,PG,130000000.0,6.317446e+08,2008-06-04,Animation,90.0,7.5,390478.0,The Dragon Warrior has to clash against the sa...
404,412,Up,PG,175000000.0,7.350991e+08,2009-05-13,Animation,96.0,8.2,867393.0,Seventy-eight year old Carl Fredricksen travel...
412,421,Despicable Me,PG,69000000.0,5.435140e+08,2010-07-08,Animation,95.0,7.6,473121.0,When a criminal mastermind uses a trio of orph...
417,426,Megamind,PG,130000000.0,3.218872e+08,2010-10-28,Animation,95.0,7.2,212563.0,The supervillain Megamind finally defeats his ...
420,429,How to Train Your Dragon,PG,165000000.0,4.948788e+08,2010-03-05,Animation,98.0,8.1,624128.0,A hapless young Viking who aspires to hunt dra...
426,436,Tangled,PG,260000000.0,5.917949e+08,2010-11-24,Animation,100.0,7.7,374981.0,The magically long-haired Rapunzel has spent h...
441,452,Kung Fu Panda 2,PG,150000000.0,6.656923e+08,2011-05-25,Animation,91.0,7.2,234612.0,Po and his friends fight to stop a peacock vil...
450,462,Hotel Transylvania,PG,85000000.0,3.583756e+08,2012-09-20,Animation,91.0,7.1,208916.0,"Dracula, who operates a high-end resort away f..."
455,467,Wreck-It Ralph,PG,165000000.0,4.712229e+08,2012-11-01,Animation,108.0,7.7,354202.0,A video game villain wants to be a hero and se...
457,469,Brave,PG,185000000.0,5.389832e+08,2012-06-21,Animation,93.0,7.1,346490.0,"Determined to make her own path in life, Princ..."
468,481,Despicable Me 2,PG,76000000.0,9.707619e+08,2013-06-25,Animation,98.0,7.4,350582.0,"When Gru, the worlds most super-bad turned sup..."
472,485,The Croods,PG,135000000.0,5.851789e+08,2013-03-20,Animation,98.0,7.2,180043.0,"After their cave is destroyed, a caveman famil..."
473,486,Frozen,PG,150000000.0,1.274219e+09,2013-11-27,Animation,102.0,7.5,527284.0,When the newly-crowned Queen Elsa accidentally...
484,499,The Lego Movie,PG,60000000.0,4.691607e+08,2014-02-06,Animation,100.0,7.8,309295.0,"An ordinary LEGO construction worker, thought ..."
489,504,How to Train Your Dragon 2,PG,145000000.0,6.091230e+08,2014-06-12,Animation,102.0,7.8,285394.0,When Hiccup and Toothless discover an ice cave...
491,506,Big Hero 6,PG,165000000.0,6.521054e+08,2014-10-24,Animation,102.0,7.8,380953.0,The special bond that develops between plus-si...

In [170]:
# Get rid of the last row, the one containing NaN for each column (use drop() method and row index)
# movies.dropna(inplace=True)
# movies



# movies.reset_index(inplace=True, drop=True)
movies

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary
0,16,The Little Mermaid,PG,40000000.0,2.223000e+08,1989-11-17,Animation,83.0,7.6,219221.0,A mermaid princess makes a Faustian bargain in...
1,47,Beauty and the Beast,PG,25000000.0,3.773506e+08,1991-11-13,Animation,84.0,8.0,397467.0,A prince cursed to spend his days as a hideous...
2,189,The Prince of Egypt,PG,70000000.0,2.186132e+08,1998-12-15,Animation,99.0,7.1,110340.0,An Egyptian prince learns of his identity as a...
3,216,Tarzan,PG,150000000.0,4.480000e+08,1999-06-18,Animation,88.0,7.3,187724.0,A man raised by gorillas must decide where he ...
4,242,Shrek,PG,60000000.0,4.844092e+08,2001-05-16,Animation,90.0,7.8,574978.0,A mean lord exiles fairytale creatures to the ...
5,262,Ice Age,PG,59000000.0,3.832571e+08,2002-03-10,Animation,81.0,7.5,411963.0,"Set during the Ice Age, a sabertooth tiger, a ..."
6,305,The Incredibles,PG,92000000.0,6.314421e+08,2004-11-05,Animation,115.0,8.0,617102.0,"A family of undercover superheroes, while tryi..."
7,312,Shrek 2,PG,150000000.0,9.198388e+08,2004-05-19,Animation,93.0,7.2,391295.0,Princess Fionas parents invite her and Shrek t...
8,386,Kung Fu Panda,PG,130000000.0,6.317446e+08,2008-06-04,Animation,90.0,7.5,390478.0,The Dragon Warrior has to clash against the sa...
9,412,Up,PG,175000000.0,7.350991e+08,2009-05-13,Animation,96.0,8.2,867393.0,Seventy-eight year old Carl Fredricksen travel...
10,421,Despicable Me,PG,69000000.0,5.435140e+08,2010-07-08,Animation,95.0,7.6,473121.0,When a criminal mastermind uses a trio of orph...
11,426,Megamind,PG,130000000.0,3.218872e+08,2010-10-28,Animation,95.0,7.2,212563.0,The supervillain Megamind finally defeats his ...
12,429,How to Train Your Dragon,PG,165000000.0,4.948788e+08,2010-03-05,Animation,98.0,8.1,624128.0,A hapless young Viking who aspires to hunt dra...
13,436,Tangled,PG,260000000.0,5.917949e+08,2010-11-24,Animation,100.0,7.7,374981.0,The magically long-haired Rapunzel has spent h...
14,452,Kung Fu Panda 2,PG,150000000.0,6.656923e+08,2011-05-25,Animation,91.0,7.2,234612.0,Po and his friends fight to stop a peacock vil...
15,462,Hotel Transylvania,PG,85000000.0,3.583756e+08,2012-09-20,Animation,91.0,7.1,208916.0,"Dracula, who operates a high-end resort away f..."
16,467,Wreck-It Ralph,PG,165000000.0,4.712229e+08,2012-11-01,Animation,108.0,7.7,354202.0,A video game villain wants to be a hero and se...
17,469,Brave,PG,185000000.0,5.389832e+08,2012-06-21,Animation,93.0,7.1,346490.0,"Determined to make her own path in life, Princ..."
18,481,Despicable Me 2,PG,76000000.0,9.707619e+08,2013-06-25,Animation,98.0,7.4,350582.0,"When Gru, the worlds most super-bad turned sup..."
19,485,The Croods,PG,135000000.0,5.851789e+08,2013-03-20,Animation,98.0,7.2,180043.0,"After their cave is destroyed, a caveman famil..."
20,486,Frozen,PG,150000000.0,1.274219e+09,2013-11-27,Animation,102.0,7.5,527284.0,When the newly-crowned Queen Elsa accidentally...
21,499,The Lego Movie,PG,60000000.0,4.691607e+08,2014-02-06,Animation,100.0,7.8,309295.0,"An ordinary LEGO construction worker, thought ..."
22,504,How to Train Your Dragon 2,PG,145000000.0,6.091230e+08,2014-06-12,Animation,102.0,7.8,285394.0,When Hiccup and Toothless discover an ice cave...
23,506,Big Hero 6,PG,165000000.0,6.521054e+08,2014-10-24,Animation,102.0,7.8,380953.0,The special bond that develops between plus-si...

In [61]:
df[['Gross', 'Budget']].mean()

Gross     4.453221e+08
Budget    9.491710e+07
dtype: float64

In [63]:
# use the fillna() method to replace the missing values of Rating with their median
df.fillna(df["Rating"].median())

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary
0,1,Look Who's Talking,PG-13,7500000.0,2.960000e+08,1989-10-12,Romance,93.0,5.9,73638.0,"After a single, career-minded woman is left on..."
1,2,Driving Miss Daisy,PG,7500000.0,1.457933e+08,1989-12-13,Comedy,99.0,7.4,91075.0,An old Jewish woman and her African-American c...
2,3,Turner & Hooch,PG,13000000.0,7.107992e+07,1989-07-28,Crime,100.0,7.2,91415.0,"Det. Scott Turner (Tom Hanks) is an uptight, b..."
3,4,Born on the Fourth of July,R,14000000.0,1.610017e+08,1989-12-20,War,145.0,7.2,91415.0,The biography of Ron Kovic. Paralyzed in the V...
4,5,Field of Dreams,PG,15000000.0,8.443162e+07,1989-04-21,Drama,107.0,7.5,101702.0,"An Iowa corn farmer, hearing voices, interpret..."
...,...,...,...,...,...,...,...,...,...,...,...
611,612,Toy Story 4,G,200000000.0,1.062000e+09,2019-06-11,Animation,100.0,6.9,6.9,6.9
612,613,Fast & Furious Presents: Hobbs & Shaw,PG-13,200000000.0,7.594000e+08,2019-07-13,Thriller,136.0,6.9,6.9,6.9
613,614,The Lion King,PG,250000000.0,1.632000e+09,2019-07-09,Drama,118.0,6.9,6.9,6.9
614,615,Avengers: Endgame,PG-13,356000000.0,2.796000e+09,2019-04-22,Action,181.0,6.9,6.9,6.9
615,0,6.9,6.9,6.9,6.900000e+00,6.9,6.9,6.9,6.9,6.9,6.9

In [7]:
pd.options.display.max_info_columns

100

In [64]:
# Drop the duplicates, if any
df.drop_duplicates()

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary
0,1,Look Who's Talking,PG-13,7500000.0,2.960000e+08,1989-10-12,Romance,93.0,5.9,73638.0,"After a single, career-minded woman is left on..."
1,2,Driving Miss Daisy,PG,7500000.0,1.457933e+08,1989-12-13,Comedy,99.0,7.4,91075.0,An old Jewish woman and her African-American c...
2,3,Turner & Hooch,PG,13000000.0,7.107992e+07,1989-07-28,Crime,100.0,7.2,91415.0,"Det. Scott Turner (Tom Hanks) is an uptight, b..."
3,4,Born on the Fourth of July,R,14000000.0,1.610017e+08,1989-12-20,War,145.0,7.2,91415.0,The biography of Ron Kovic. Paralyzed in the V...
4,5,Field of Dreams,PG,15000000.0,8.443162e+07,1989-04-21,Drama,107.0,7.5,101702.0,"An Iowa corn farmer, hearing voices, interpret..."
...,...,...,...,...,...,...,...,...,...,...,...
611,612,Toy Story 4,G,200000000.0,1.062000e+09,2019-06-11,Animation,100.0,NaN,NaN,NaN
612,613,Fast & Furious Presents: Hobbs & Shaw,PG-13,200000000.0,7.594000e+08,2019-07-13,Thriller,136.0,NaN,NaN,NaN
613,614,The Lion King,PG,250000000.0,1.632000e+09,2019-07-09,Drama,118.0,NaN,NaN,NaN
614,615,Avengers: Endgame,PG-13,356000000.0,2.796000e+09,2019-04-22,Action,181.0,NaN,NaN,NaN
615,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [66]:
# importing pandas as pd
import pandas as pd
 
# Making data frame from the csv file
df = pd.read_csv("movies_2.csv")
df[:10]

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary
0,1,Look Who's Talking,PG-13,7500000.0,296000000.0,1989-10-12,Romance,93.0,5.9,73638.0,"After a single, career-minded woman is left on..."
1,2,Driving Miss Daisy,PG,7500000.0,145793296.0,1989-12-13,Comedy,99.0,7.4,91075.0,An old Jewish woman and her African-American c...
2,3,Turner & Hooch,PG,13000000.0,71079915.0,1989-07-28,Crime,100.0,7.2,91415.0,"Det. Scott Turner (Tom Hanks) is an uptight, b..."
3,4,Born on the Fourth of July,R,14000000.0,161001698.0,1989-12-20,War,145.0,7.2,91415.0,The biography of Ron Kovic. Paralyzed in the V...
4,5,Field of Dreams,PG,15000000.0,84431625.0,1989-04-21,Drama,107.0,7.5,101702.0,"An Iowa corn farmer, hearing voices, interpret..."
5,6,Uncle Buck,PG,15000000.0,79258538.0,1989-08-16,Family,100.0,7.0,77659.0,Bachelor and all-round slob Buck babysits his ...
6,7,When Harry Met Sally...,R,16000000.0,92800000.0,1989-07-21,Romance,96.0,7.6,180871.0,Harry and Sally have known each other for year...
7,8,Dead Poets Society,PG,16400000.0,235860116.0,1989-06-02,Drama,129.0,8.1,382002.0,English teacher John Keating inspires his stud...
8,9,Parenthood,PG-13,20000000.0,126297830.0,1989-07-31,Comedy,124.0,7.0,41866.0,The Buckmans are a midwestern family all deali...
9,10,Lethal Weapon 2,R,25000000.0,227853986.0,1989-07-07,Comedy,114.0,7.2,151737.0,Riggs and Murtaugh are on the trail of South A...

In [173]:
# Convert Budget into integer type (use the astype() method)
df = df.astype("Budget",int) 
# df = df.astype ['Budget':integer]
# df('Budget') = df('Budget').astype('int')
df ['Budget']

TypeError: data type 'Budget' not understood

In [129]:
# Convert Gross into integer type
# df = df.astype(dtype, 'Gross':'int')
# df('Gross') = df('Gross').astype('int')

In [ ]:
# Convert Release Date into date type (use the to_datetime method)

show the movies with more than 7 in Rating & greater than 50 million Gross

In [148]:
#if [df["Rating"] > 7 and movie["Gross"] > 50]

In [136]:
from datetime import datetime
# date 

# release_date_str = '2022-07-25'  # example release date string

# release_date = datetime.strptime(release_date_str, '%Y-%m-%d')

# release_date is now a datetime object
# print(type(release_date))  # Output: <class 'datetime.datetime'>

show the movies with more than 7 in Rating & greater than 50 million Gross & with Parental guidance as MPAA Rating

In [163]:
# movies in Rating > 7, Gross > 50 million, and MPAA Rating = 'PG'
movies = movies[(movies['Rating'] > 7) & (movies['Gross'] >  50000000) & (movies['MPAA Rating'] == 'PG')]
print(movies)

     MovieID                       Title MPAA Rating       Budget  \
15        16          The Little Mermaid          PG   40000000.0
46        47        Beauty and the Beast          PG   25000000.0
188      189         The Prince of Egypt          PG   70000000.0
215      216                      Tarzan          PG  150000000.0
241      242                       Shrek          PG   60000000.0
261      262                     Ice Age          PG   59000000.0
304      305             The Incredibles          PG   92000000.0
311      312                     Shrek 2          PG  150000000.0
382      386               Kung Fu Panda          PG  130000000.0
404      412                          Up          PG  175000000.0
412      421               Despicable Me          PG   69000000.0
417      426                    Megamind          PG  130000000.0
420      429    How to Train Your Dragon          PG  165000000.0
426      436                     Tangled          PG  260000000.0
441      452             Kung Fu Panda 2          PG  150000000.0
450      462          Hotel Transylvania          PG   85000000.0
455      467              Wreck-It Ralph          PG  165000000.0
457      469                       Brave          PG  185000000.0
468      481             Despicable Me 2          PG   76000000.0
472      485                  The Croods          PG  135000000.0
473      486                      Frozen          PG  150000000.0
484      499              The Lego Movie          PG   60000000.0
489      504  How to Train Your Dragon 2          PG  145000000.0
491      506                  Big Hero 6          PG  165000000.0

            Gross Release Date      Genre  Runtime  Rating  Rating Count  \
15   2.223000e+08   1989-11-17  Animation     83.0     7.6      219221.0
46   3.773506e+08   1991-11-13  Animation     84.0     8.0      397467.0
188  2.186132e+08   1998-12-15  Animation     99.0     7.1      110340.0
215  4.480000e+08   1999-06-18  Animation     88.0     7.3      187724.0
241  4.844092e+08   2001-05-16  Animation     90.0     7.8      574978.0
261  3.832571e+08   2002-03-10  Animation     81.0     7.5      411963.0
304  6.314421e+08   2004-11-05  Animation    115.0     8.0      617102.0
311  9.198388e+08   2004-05-19  Animation     93.0     7.2      391295.0
382  6.317446e+08   2008-06-04  Animation     90.0     7.5      390478.0
404  7.350991e+08   2009-05-13  Animation     96.0     8.2      867393.0
412  5.435140e+08   2010-07-08  Animation     95.0     7.6      473121.0
417  3.218872e+08   2010-10-28  Animation     95.0     7.2      212563.0
420  4.948788e+08   2010-03-05  Animation     98.0     8.1      624128.0
426  5.917949e+08   2010-11-24  Animation    100.0     7.7      374981.0
441  6.656923e+08   2011-05-25  Animation     91.0     7.2      234612.0
450  3.583756e+08   2012-09-20  Animation     91.0     7.1      208916.0
455  4.712229e+08   2012-11-01  Animation    108.0     7.7      354202.0
457  5.389832e+08   2012-06-21  Animation     93.0     7.1      346490.0
468  9.707619e+08   2013-06-25  Animation     98.0     7.4      350582.0
472  5.851789e+08   2013-03-20  Animation     98.0     7.2      180043.0
473  1.274219e+09   2013-11-27  Animation    102.0     7.5      527284.0
484  4.691607e+08   2014-02-06  Animation    100.0     7.8      309295.0
489  6.091230e+08   2014-06-12  Animation    102.0     7.8      285394.0
491  6.521054e+08   2014-10-24  Animation    102.0     7.8      380953.0

                                               Summary
15   A mermaid princess makes a Faustian bargain in...
46   A prince cursed to spend his days as a hideous...
188  An Egyptian prince learns of his identity as a...
215  A man raised by gorillas must decide where he ...
241  A mean lord exiles fairytale creatures to the ...
261  Set during the Ice Age, a sabertooth tiger, a ...
304  A family of undercover superheroes, while tryi...
311  Princess Fionas parents invite her and Shrek t...
382  The Dragon Warrior has to clash against the sa...
404  Seventy-eight year old Carl Fredricksen travel...
412  When a criminal mastermind uses a trio of orph...
417  The supervillain Megamind finally defeats his ...
420  A hapless young Viking who aspires to hunt dra...
426  The magically long-haired Rapunzel has spent h...
441  Po and his friends fight to stop a peacock vil...
450  Dracula, who operates a high-end resort away f...
455  A video game villain wants to be a hero and se...
457  Determined to make her own path in life, Princ...
468  When Gru, the worlds most super-bad turned sup...
472  After their cave is destroyed, a caveman famil...
473  When the newly-crowned Queen Elsa accidentally...
484  An ordinary LEGO construction worker, thought ...
489  When Hiccup and Toothless discover an ice cave...
491  The special bond that develops between plus-si...

show the count of Animation movies with more than 7 in Rating (use the shape() method)

In [127]:
import pandas as pd
import numpy as np

movies = movies[movies['Genre'] == 'Animation']  # filter for animation movies

# movies['Rating'] = pd.to_numeric(Animation_movies['rating'])

# count_high_rated_animation = len(animation_movies[animation_movies['rating'] > 7])

# print(f"Number of animation movies with ratings > 7: {count_high_rated_animation}")

show the top 5 movies based on Budget

In [138]:
import pandas as pd
import numpy as np
movies_df = pd.read_csv('movies_2.csv')
movies_df
# movies_df = movies_df[movies_df['Budget'].notna()].sort_values(by='Budget', ascending=False)
top_5_movies = movies_df.head(5)
print(top_5_movies[['MovieID', 'Budget']])

   MovieID      Budget
0        1   7500000.0
1        2   7500000.0
2        3  13000000.0
3        4  14000000.0
4        5  15000000.0

In [151]:
# show the top 5 movies based on Budget
df.sort_values("Budget", ascending=False).head(5)

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary
594,595,Avengers: Infinity War,PG-13,400000000.0,2.048000e+09,2018-04-23,Action,149.0,NaN,NaN,NaN
454,455,Pirates of the Caribbean: On Stranger Tides,PG-13,380000000.0,1.045714e+09,2011-05-14,Action,136.0,6.6,455211.0,Jack Sparrow and Barbossa embark on a quest to...
614,615,Avengers: Endgame,PG-13,356000000.0,2.796000e+09,2019-04-22,Action,181.0,NaN,NaN,NaN
574,575,Star Wars: The Last Jedi,PG-13,317000000.0,1.333000e+09,2019-12-09,Science Fiction,152.0,NaN,NaN,NaN
375,376,Pirates of the Caribbean: At World's End,PG-13,300000000.0,9.610000e+08,2007-05-19,Adventure,169.0,7.1,565402.0,"Captain Barbossa, Will Turner and Elizabeth Sw..."

In [152]:

# show the top 5 Comedy movies by Rating

df[df['Genre'] == "Comedy"]
df[df['Genre'] == "Comedy"].sort_values("Rating", ascending=False).head(5)

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary
111,112,Forrest Gump,PG-13,55000000.0,677945399.0,1994-07-06,Comedy,142.0,8.8,1657851.0,"The presidencies of Kennedy and Johnson, the e..."
185,186,The Truman Show,PG,60000000.0,264118201.0,1998-06-04,Comedy,103.0,8.1,859224.0,An insurance salesman discovers his whole life...
80,81,Groundhog Day,PG,14600000.0,70906973.0,1993-02-11,Comedy,101.0,8.0,549538.0,A weatherman finds himself inexplicably living...
254,255,"Monsters, Inc.",G,115000000.0,562816256.0,2001-11-01,Comedy,92.0,8.0,758349.0,"In order to power the city, monsters have to s..."
316,317,The 40 Year Old Virgin,R,26000000.0,109449237.0,2005-08-11,Comedy,116.0,7.7,500448.0,"Goaded by his buddies, a nerdy guy who's never..."

In [153]:
# top 5 movie names by Rating

df.sort_values("Rating", ascending=False).head(5)

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary
393,394,The Dark Knight,PG-13,185000000.0,1.004558e+09,2008-07-16,Action,152.0,9.0,2127228.0,When the menace known as the Joker wreaks havo...
98,99,Jurassic Park III,PG-13,93000000.0,3.688000e+08,2001-07-16,Thriller,92.0,8.9,1690474.0,A decidedly odd couple with ulterior motives ...
287,288,The Lord of the Rings: The Return of the King,PG-13,94000000.0,1.118889e+09,2003-12-01,Fantasy,201.0,8.9,1529953.0,Gandalf and Aragorn lead the World of Men agai...
99,100,Pulp Fiction,R,8000000.0,2.139288e+08,1994-09-10,Thriller,154.0,8.9,1690474.0,"The lives of two mob hitmen, a boxer, a gangst..."
83,84,Schindler's List,R,22000000.0,3.213656e+08,1993-11-29,History,195.0,8.9,1117322.0,"In German-occupied Poland during World War II,..."

In [ ]:
# top 3 high Gross Romance movies released after 1999 (typecast it to datetime)

from datetime import datetime
df[(df['Genre'] == "Romance") & (df["Release_Date"] > datetime.time("1999-12-31", "%Y-%m-%d"))].sort_values("Gross", ascending=False).head(3)

KeyError: 'ReleaseDate'

In [159]:
# how many Genres are present in the dataframe? (use value_counts() method which applies to Series, not Dataframe)
Genre_series = df['Genre'].explode()
Genre_series.value_counts()

Genre
Action             110
Comedy              99
Animation           87
Drama               66
Thriller            41
Science Fiction     37
Adventure           30
Family              29
Romance             28
Fantasy             27
Crime               17
Horror              14
Mystery             11
War                  9
Western              6
History              4
Name: count, dtype: int64

In [161]:
# top 5 most expensive movies released after 1999 (measured by Budget)
df[df["Release_Date"] > datetime.strptime("1999-12-31", "%Y-%m-%d")].sort_values("Budget", ascending=False).head(3)

KeyError: 'Release_Date'