In [4]:
import numpy as np
import pandas as pd
df = pd.read_csv("movies_2.csv")
df

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary
0,1,Look Who's Talking,PG-13,7500000.0,2.960000e+08,1989-10-12,Romance,93.0,5.9,73638.0,"After a single, career-minded woman is left on..."
1,2,Driving Miss Daisy,PG,7500000.0,1.457933e+08,1989-12-13,Comedy,99.0,7.4,91075.0,An old Jewish woman and her African-American c...
2,3,Turner & Hooch,PG,13000000.0,7.107992e+07,1989-07-28,Crime,100.0,7.2,91415.0,"Det. Scott Turner (Tom Hanks) is an uptight, b..."
3,4,Born on the Fourth of July,R,14000000.0,1.610017e+08,1989-12-20,War,145.0,7.2,91415.0,The biography of Ron Kovic. Paralyzed in the V...
4,5,Field of Dreams,PG,15000000.0,8.443162e+07,1989-04-21,Drama,107.0,7.5,101702.0,"An Iowa corn farmer, hearing voices, interpret..."
...,...,...,...,...,...,...,...,...,...,...,...
611,612,Toy Story 4,G,200000000.0,1.062000e+09,2019-06-11,Animation,100.0,NaN,NaN,NaN
612,613,Fast & Furious Presents: Hobbs & Shaw,PG-13,200000000.0,7.594000e+08,2019-07-13,Thriller,136.0,NaN,NaN,NaN
613,614,The Lion King,PG,250000000.0,1.632000e+09,2019-07-09,Drama,118.0,NaN,NaN,NaN
614,615,Avengers: Endgame,PG-13,356000000.0,2.796000e+09,2019-04-22,Action,181.0,NaN,NaN,NaN
615,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#the number of rows and columns present in the data set (i.e. the shape of the dataframe)
# df.head(5)
print(df.shape)

(616, 11)

In [ ]:
#columns present in the data set, along with the data type (use info or dtypes method)
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 616 entries, 0 to 615
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   MovieID       616 non-null    int64
 1   Title         615 non-null    object
 2   MPAA Rating   615 non-null    object
 3   Budget        615 non-null    float64
 4   Gross         615 non-null    float64
 5   Release Date  615 non-null    object
 6   Genre         615 non-null    object
 7   Runtime       615 non-null    float64
 8   Rating        508 non-null    float64
 9   Rating Count  508 non-null    float64
 10  Summary       496 non-null    object
dtypes: float64(5), int64(1), object(5)
memory usage: 53.1+ KB
None

In [ ]:
#columns present in the data set, along with the data type (use info or dtypes method)
print(df.dtypes)

MovieID           int64
Title            object
MPAA Rating      object
Budget          float64
Gross           float64
Release Date     object
Genre            object
Runtime         float64
Rating          float64
Rating Count    float64
Summary          object
dtype: object

In [ ]:
#check how many NaN we have for MPAA Rating, Budget, Gross, Release Date, Genre, Runtime, 
# Rating and Rating Count columns
print(df.isna().sum())
# df.isnull().sum()

MovieID           0
Title             1
MPAA Rating       1
Budget            1
Gross             1
Release Date      1
Genre             1
Runtime           1
Rating          108
Rating Count    108
Summary         120
dtype: int64

In [213]:
# Get rid of the Summary column (use the drop() method)
new_df = df.drop('Summary', axis='columns') # (column = 1, row = 0)
new_df

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count
0,1,Look Who's Talking,PG-13,7500000.0,2.960000e+08,1989-10-12,Romance,93.0,5.9,73638.0
1,2,Driving Miss Daisy,PG,7500000.0,1.457933e+08,1989-12-13,Comedy,99.0,7.4,91075.0
2,3,Turner & Hooch,PG,13000000.0,7.107992e+07,1989-07-28,Crime,100.0,7.2,91415.0
3,4,Born on the Fourth of July,R,14000000.0,1.610017e+08,1989-12-20,War,145.0,7.2,91415.0
4,5,Field of Dreams,PG,15000000.0,8.443162e+07,1989-04-21,Drama,107.0,7.5,101702.0
...,...,...,...,...,...,...,...,...,...,...
611,612,Toy Story 4,G,200000000.0,1.062000e+09,2019-06-11,Animation,100.0,NaN,NaN
612,613,Fast & Furious Presents: Hobbs & Shaw,PG-13,200000000.0,7.594000e+08,2019-07-13,Thriller,136.0,NaN,NaN
613,614,The Lion King,PG,250000000.0,1.632000e+09,2019-07-09,Drama,118.0,NaN,NaN
614,615,Avengers: Endgame,PG-13,356000000.0,2.796000e+09,2019-04-22,Action,181.0,NaN,NaN
615,0,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN

In [214]:
# use the rename method to change all columns names to lowercase, 
# and replace spaces with underscores if the name is made of more than one word
renamed = df.rename(columns={ "MovieID": "movies", "Gross": "Profit"})
renamed.to_csv("output.csv")
renamed

,movies,Title,MPAA Rating,Budget,Profit,Release Date,Genre,Runtime,Rating,Rating Count,Summary
0,1,Look Who's Talking,PG-13,7500000.0,2.960000e+08,1989-10-12,Romance,93.0,5.9,73638.0,"After a single, career-minded woman is left on..."
1,2,Driving Miss Daisy,PG,7500000.0,1.457933e+08,1989-12-13,Comedy,99.0,7.4,91075.0,An old Jewish woman and her African-American c...
2,3,Turner & Hooch,PG,13000000.0,7.107992e+07,1989-07-28,Crime,100.0,7.2,91415.0,"Det. Scott Turner (Tom Hanks) is an uptight, b..."
3,4,Born on the Fourth of July,R,14000000.0,1.610017e+08,1989-12-20,War,145.0,7.2,91415.0,The biography of Ron Kovic. Paralyzed in the V...
4,5,Field of Dreams,PG,15000000.0,8.443162e+07,1989-04-21,Drama,107.0,7.5,101702.0,"An Iowa corn farmer, hearing voices, interpret..."
...,...,...,...,...,...,...,...,...,...,...,...
611,612,Toy Story 4,G,200000000.0,1.062000e+09,2019-06-11,Animation,100.0,NaN,NaN,NaN
612,613,Fast & Furious Presents: Hobbs & Shaw,PG-13,200000000.0,7.594000e+08,2019-07-13,Thriller,136.0,NaN,NaN,NaN
613,614,The Lion King,PG,250000000.0,1.632000e+09,2019-07-09,Drama,118.0,NaN,NaN,NaN
614,615,Avengers: Endgame,PG-13,356000000.0,2.796000e+09,2019-04-22,Action,181.0,NaN,NaN,NaN
615,0,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN

In [223]:
# Get rid of the last row, the one containing NaN for each column (use drop() method and row index)
# df1 = df.dropna(inplace=True)
# df1
# # movies.reset_index(inplace=True, drop=True)
# # df

In [226]:
describe_values = df.describe()
describe_values

,MovieID,Budget,Gross,Release Date,Runtime,Rating,Rating Count
count,496.000000,4.960000e+02,4.960000e+02,496,496.000000,496.000000,4.960000e+02
mean,250.858871,8.334580e+07,3.811076e+08,2001-10-05 11:22:15.483870976,117.616935,6.912500,3.338205e+05
min,1.000000,6.000000e+04,5.300000e+07,1989-04-21 00:00:00,79.000000,4.100000,1.491800e+04
25%,124.750000,3.500000e+07,1.912070e+08,1995-06-05 12:00:00,100.000000,6.400000,1.256288e+05
50%,248.500000,7.000000e+07,3.064765e+08,2001-08-03 00:00:00,115.000000,6.900000,2.369415e+05
75%,374.250000,1.207500e+08,4.783602e+08,2007-12-13 00:00:00,130.000000,7.525000,4.141690e+05
max,510.000000,3.800000e+08,2.787965e+09,2014-12-11 00:00:00,201.000000,9.000000,2.127228e+06
std,146.574600,5.965585e+07,2.798189e+08,NaN,22.683470,0.876843,3.156063e+05

In [229]:
Avg = df[['Gross', 'Budget']].mean()
Avg

Gross     3.811076e+08
Budget    8.334580e+07
dtype: float64

In [230]:
print('null values', df.isna().any())

null values MovieID         False
Title           False
MPAA Rating     False
Budget          False
Gross           False
Release Date    False
Genre           False
Runtime         False
Rating          False
Rating Count    False
Summary         False
dtype: bool

In [232]:
# use the fillna() method to replace the missing values of Rating with their median
null_val = df.fillna(df["Rating"].median())
null_val

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary
0,1,Look Who's Talking,PG-13,7500000.0,296000000.0,1989-10-12,Romance,93.0,5.9,73638.0,"After a single, career-minded woman is left on..."
1,2,Driving Miss Daisy,PG,7500000.0,145793296.0,1989-12-13,Comedy,99.0,7.4,91075.0,An old Jewish woman and her African-American c...
2,3,Turner & Hooch,PG,13000000.0,71079915.0,1989-07-28,Crime,100.0,7.2,91415.0,"Det. Scott Turner (Tom Hanks) is an uptight, b..."
3,4,Born on the Fourth of July,R,14000000.0,161001698.0,1989-12-20,War,145.0,7.2,91415.0,The biography of Ron Kovic. Paralyzed in the V...
4,5,Field of Dreams,PG,15000000.0,84431625.0,1989-04-21,Drama,107.0,7.5,101702.0,"An Iowa corn farmer, hearing voices, interpret..."
...,...,...,...,...,...,...,...,...,...,...,...
505,506,Big Hero 6,PG,165000000.0,652105443.0,2014-10-24,Animation,102.0,7.8,380953.0,The special bond that develops between plus-si...
506,507,Interstellar,PG-13,165000000.0,675120017.0,2014-11-05,Science Fiction,169.0,8.6,1343549.0,A team of explorers travel through a wormhole ...
507,508,Captain America: The Winter Soldier,PG-13,170000000.0,714766572.0,2014-03-20,Action,136.0,7.7,685903.0,As Steve Rogers struggles to embrace his role ...
508,509,Dawn of the Planet of the Apes,PG-13,170000000.0,710644566.0,2014-06-26,Science Fiction,130.0,7.6,395425.0,A growing nation of genetically evolved apes l...
509,510,Guardians of the Galaxy,PG-13,170000000.0,773328629.0,2014-07-30,Action,121.0,8.0,978222.0,A group of intergalactic criminals must pull t...

In [233]:
df_without_summary=df.drop("Summary", axis = 1)
df_without_summary

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count
0,1,Look Who's Talking,PG-13,7500000.0,296000000.0,1989-10-12,Romance,93.0,5.9,73638.0
1,2,Driving Miss Daisy,PG,7500000.0,145793296.0,1989-12-13,Comedy,99.0,7.4,91075.0
2,3,Turner & Hooch,PG,13000000.0,71079915.0,1989-07-28,Crime,100.0,7.2,91415.0
3,4,Born on the Fourth of July,R,14000000.0,161001698.0,1989-12-20,War,145.0,7.2,91415.0
4,5,Field of Dreams,PG,15000000.0,84431625.0,1989-04-21,Drama,107.0,7.5,101702.0
...,...,...,...,...,...,...,...,...,...,...
505,506,Big Hero 6,PG,165000000.0,652105443.0,2014-10-24,Animation,102.0,7.8,380953.0
506,507,Interstellar,PG-13,165000000.0,675120017.0,2014-11-05,Science Fiction,169.0,8.6,1343549.0
507,508,Captain America: The Winter Soldier,PG-13,170000000.0,714766572.0,2014-03-20,Action,136.0,7.7,685903.0
508,509,Dawn of the Planet of the Apes,PG-13,170000000.0,710644566.0,2014-06-26,Science Fiction,130.0,7.6,395425.0
509,510,Guardians of the Galaxy,PG-13,170000000.0,773328629.0,2014-07-30,Action,121.0,8.0,978222.0

In [234]:
AVG_GR_BUD= df[['Gross', 'Budget']].mean()
AVG_GR_BUD

Gross     3.811076e+08
Budget    8.334580e+07
dtype: float64

In [235]:
DF2 = df.astype({"Budget":int,"Gross":int})
DF2

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary
0,1,Look Who's Talking,PG-13,7500000,296000000,1989-10-12,Romance,93.0,5.9,73638.0,"After a single, career-minded woman is left on..."
1,2,Driving Miss Daisy,PG,7500000,145793296,1989-12-13,Comedy,99.0,7.4,91075.0,An old Jewish woman and her African-American c...
2,3,Turner & Hooch,PG,13000000,71079915,1989-07-28,Crime,100.0,7.2,91415.0,"Det. Scott Turner (Tom Hanks) is an uptight, b..."
3,4,Born on the Fourth of July,R,14000000,161001698,1989-12-20,War,145.0,7.2,91415.0,The biography of Ron Kovic. Paralyzed in the V...
4,5,Field of Dreams,PG,15000000,84431625,1989-04-21,Drama,107.0,7.5,101702.0,"An Iowa corn farmer, hearing voices, interpret..."
...,...,...,...,...,...,...,...,...,...,...,...
505,506,Big Hero 6,PG,165000000,652105443,2014-10-24,Animation,102.0,7.8,380953.0,The special bond that develops between plus-si...
506,507,Interstellar,PG-13,165000000,675120017,2014-11-05,Science Fiction,169.0,8.6,1343549.0,A team of explorers travel through a wormhole ...
507,508,Captain America: The Winter Soldier,PG-13,170000000,714766572,2014-03-20,Action,136.0,7.7,685903.0,As Steve Rogers struggles to embrace his role ...
508,509,Dawn of the Planet of the Apes,PG-13,170000000,710644566,2014-06-26,Science Fiction,130.0,7.6,395425.0,A growing nation of genetically evolved apes l...
509,510,Guardians of the Galaxy,PG-13,170000000,773328629,2014-07-30,Action,121.0,8.0,978222.0,A group of intergalactic criminals must pull t...

In [132]:
# df["Release date"]= pd.to_datetime(["Release date"])
# df.dtypes

df['Release Date'] = pd.to_datetime(df['Release Date'])
print(df.dtypes)
df

MovieID                  int64
Title                   object
MPAA Rating             object
Budget                 float64
Gross                  float64
Release Date    datetime64[ns]
Genre                   object
Runtime                float64
Rating                 float64
Rating Count           float64
Summary                 object
dtype: object

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary
1,2,Driving Miss Daisy,PG,7500000.0,145793296.0,1989-12-13,Comedy,99.0,7.4,91075.0,An old Jewish woman and her African-American c...
2,3,Turner & Hooch,PG,13000000.0,71079915.0,1989-07-28,Crime,100.0,7.2,91415.0,"Det. Scott Turner (Tom Hanks) is an uptight, b..."
4,5,Field of Dreams,PG,15000000.0,84431625.0,1989-04-21,Drama,107.0,7.5,101702.0,"An Iowa corn farmer, hearing voices, interpret..."
7,8,Dead Poets Society,PG,16400000.0,235860116.0,1989-06-02,Drama,129.0,8.1,382002.0,English teacher John Keating inspires his stud...
13,14,Batman,PG,35000000.0,411348924.0,1989-06-23,Action,126.0,7.5,319517.0,The Dark Knight of Gotham City begins his war ...

In [19]:
# use the fillna() method to replace the missing values of Rating with their median
df.fillna(df["Rating"].median())

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary
0,1,Look Who's Talking,PG-13,7500000.0,2.960000e+08,1989-10-12,Romance,93.0,5.9,73638.0,"After a single, career-minded woman is left on..."
1,2,Driving Miss Daisy,PG,7500000.0,1.457933e+08,1989-12-13,Comedy,99.0,7.4,91075.0,An old Jewish woman and her African-American c...
2,3,Turner & Hooch,PG,13000000.0,7.107992e+07,1989-07-28,Crime,100.0,7.2,91415.0,"Det. Scott Turner (Tom Hanks) is an uptight, b..."
3,4,Born on the Fourth of July,R,14000000.0,1.610017e+08,1989-12-20,War,145.0,7.2,91415.0,The biography of Ron Kovic. Paralyzed in the V...
4,5,Field of Dreams,PG,15000000.0,8.443162e+07,1989-04-21,Drama,107.0,7.5,101702.0,"An Iowa corn farmer, hearing voices, interpret..."
...,...,...,...,...,...,...,...,...,...,...,...
611,612,Toy Story 4,G,200000000.0,1.062000e+09,2019-06-11,Animation,100.0,6.9,6.9,6.9
612,613,Fast & Furious Presents: Hobbs & Shaw,PG-13,200000000.0,7.594000e+08,2019-07-13,Thriller,136.0,6.9,6.9,6.9
613,614,The Lion King,PG,250000000.0,1.632000e+09,2019-07-09,Drama,118.0,6.9,6.9,6.9
614,615,Avengers: Endgame,PG-13,356000000.0,2.796000e+09,2019-04-22,Action,181.0,6.9,6.9,6.9
615,0,6.9,6.9,6.9,6.900000e+00,6.9,6.9,6.9,6.9,6.9,6.9

In [20]:
# Drop the duplicates, if any
df.drop_duplicates()

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary
0,1,Look Who's Talking,PG-13,7500000.0,2.960000e+08,1989-10-12,Romance,93.0,5.9,73638.0,"After a single, career-minded woman is left on..."
1,2,Driving Miss Daisy,PG,7500000.0,1.457933e+08,1989-12-13,Comedy,99.0,7.4,91075.0,An old Jewish woman and her African-American c...
2,3,Turner & Hooch,PG,13000000.0,7.107992e+07,1989-07-28,Crime,100.0,7.2,91415.0,"Det. Scott Turner (Tom Hanks) is an uptight, b..."
3,4,Born on the Fourth of July,R,14000000.0,1.610017e+08,1989-12-20,War,145.0,7.2,91415.0,The biography of Ron Kovic. Paralyzed in the V...
4,5,Field of Dreams,PG,15000000.0,8.443162e+07,1989-04-21,Drama,107.0,7.5,101702.0,"An Iowa corn farmer, hearing voices, interpret..."
...,...,...,...,...,...,...,...,...,...,...,...
611,612,Toy Story 4,G,200000000.0,1.062000e+09,2019-06-11,Animation,100.0,NaN,NaN,NaN
612,613,Fast & Furious Presents: Hobbs & Shaw,PG-13,200000000.0,7.594000e+08,2019-07-13,Thriller,136.0,NaN,NaN,NaN
613,614,The Lion King,PG,250000000.0,1.632000e+09,2019-07-09,Drama,118.0,NaN,NaN,NaN
614,615,Avengers: Endgame,PG-13,356000000.0,2.796000e+09,2019-04-22,Action,181.0,NaN,NaN,NaN
615,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [143]:
# importing pandas as pd
import pandas as pd
# Making data frame from the csv file
df = pd.read_csv("movies_2.csv")
df
df_top_10 = df[:10]
df_top_10

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary
0,1,Look Who's Talking,PG-13,7500000.0,296000000.0,1989-10-12,Romance,93.0,5.9,73638.0,"After a single, career-minded woman is left on..."
1,2,Driving Miss Daisy,PG,7500000.0,145793296.0,1989-12-13,Comedy,99.0,7.4,91075.0,An old Jewish woman and her African-American c...
2,3,Turner & Hooch,PG,13000000.0,71079915.0,1989-07-28,Crime,100.0,7.2,91415.0,"Det. Scott Turner (Tom Hanks) is an uptight, b..."
3,4,Born on the Fourth of July,R,14000000.0,161001698.0,1989-12-20,War,145.0,7.2,91415.0,The biography of Ron Kovic. Paralyzed in the V...
4,5,Field of Dreams,PG,15000000.0,84431625.0,1989-04-21,Drama,107.0,7.5,101702.0,"An Iowa corn farmer, hearing voices, interpret..."
5,6,Uncle Buck,PG,15000000.0,79258538.0,1989-08-16,Family,100.0,7.0,77659.0,Bachelor and all-round slob Buck babysits his ...
6,7,When Harry Met Sally...,R,16000000.0,92800000.0,1989-07-21,Romance,96.0,7.6,180871.0,Harry and Sally have known each other for year...
7,8,Dead Poets Society,PG,16400000.0,235860116.0,1989-06-02,Drama,129.0,8.1,382002.0,English teacher John Keating inspires his stud...
8,9,Parenthood,PG-13,20000000.0,126297830.0,1989-07-31,Comedy,124.0,7.0,41866.0,The Buckmans are a midwestern family all deali...
9,10,Lethal Weapon 2,R,25000000.0,227853986.0,1989-07-07,Comedy,114.0,7.2,151737.0,Riggs and Murtaugh are on the trail of South A...

In [147]:
# 1.show the movies with more than 7 in Rating & greater than 50 million Gross

df[(df['Rating'] > 7) & (df["Gross"] > 50000000)]

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary
1,2,Driving Miss Daisy,PG,7500000.0,145793296.0,1989-12-13,Comedy,99.0,7.4,91075.0,An old Jewish woman and her African-American c...
2,3,Turner & Hooch,PG,13000000.0,71079915.0,1989-07-28,Crime,100.0,7.2,91415.0,"Det. Scott Turner (Tom Hanks) is an uptight, b..."
3,4,Born on the Fourth of July,R,14000000.0,161001698.0,1989-12-20,War,145.0,7.2,91415.0,The biography of Ron Kovic. Paralyzed in the V...
4,5,Field of Dreams,PG,15000000.0,84431625.0,1989-04-21,Drama,107.0,7.5,101702.0,"An Iowa corn farmer, hearing voices, interpret..."
6,7,When Harry Met Sally...,R,16000000.0,92800000.0,1989-07-21,Romance,96.0,7.6,180871.0,Harry and Sally have known each other for year...
...,...,...,...,...,...,...,...,...,...,...,...
505,506,Big Hero 6,PG,165000000.0,652105443.0,2014-10-24,Animation,102.0,7.8,380953.0,The special bond that develops between plus-si...
506,507,Interstellar,PG-13,165000000.0,675120017.0,2014-11-05,Science Fiction,169.0,8.6,1343549.0,A team of explorers travel through a wormhole ...
507,508,Captain America: The Winter Soldier,PG-13,170000000.0,714766572.0,2014-03-20,Action,136.0,7.7,685903.0,As Steve Rogers struggles to embrace his role ...
508,509,Dawn of the Planet of the Apes,PG-13,170000000.0,710644566.0,2014-06-26,Science Fiction,130.0,7.6,395425.0,A growing nation of genetically evolved apes l...
509,510,Guardians of the Galaxy,PG-13,170000000.0,773328629.0,2014-07-30,Action,121.0,8.0,978222.0,A group of intergalactic criminals must pull t...

In [148]:
# 2.show the movies with more than 7 in Rating & greater than 50 million Gross & with Parental guidance as MPAA Rating

df[(df['Rating'] > 7) & (df['Gross'] >  50000000) & (df['MPAA Rating'] == 'PG')]
# df = df[(df['Rating'] > 7) & (df['Gross'] >  50000000) & (df['MPAA Rating'] == 'PG')].head(5)
# print(df)

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary
1,2,Driving Miss Daisy,PG,7500000.0,1.457933e+08,1989-12-13,Comedy,99.0,7.4,91075.0,An old Jewish woman and her African-American c...
2,3,Turner & Hooch,PG,13000000.0,7.107992e+07,1989-07-28,Crime,100.0,7.2,91415.0,"Det. Scott Turner (Tom Hanks) is an uptight, b..."
4,5,Field of Dreams,PG,15000000.0,8.443162e+07,1989-04-21,Drama,107.0,7.5,101702.0,"An Iowa corn farmer, hearing voices, interpret..."
7,8,Dead Poets Society,PG,16400000.0,2.358601e+08,1989-06-02,Drama,129.0,8.1,382002.0,English teacher John Keating inspires his stud...
13,14,Batman,PG,35000000.0,4.113489e+08,1989-06-23,Action,126.0,7.5,319517.0,The Dark Knight of Gotham City begins his war ...
15,16,The Little Mermaid,PG,40000000.0,2.223000e+08,1989-11-17,Animation,83.0,7.6,219221.0,A mermaid princess makes a Faustian bargain in...
16,17,Back to the Future Part II,PG,40000000.0,3.320000e+08,1989-11-20,Science Fiction,108.0,7.8,438940.0,"After visiting 2015, Marty McFly must repeat h..."
19,20,Steel Magnolias,PG,15000000.0,9.590409e+07,1989-11-15,Drama,119.0,7.3,43037.0,"A young beautician, newly arrived in a small L..."
24,25,Home Alone,PG,18000000.0,4.766847e+08,1990-11-09,Family,103.0,7.6,414472.0,An eight-year-old troublemaker must protect hi...
32,33,The Hunt for Red October,PG,30000000.0,1.992000e+08,1990-03-02,Thriller,134.0,7.6,167212.0,"In November 1984, the Soviet Unions best subma..."
34,35,Back to the Future Part III,PG,40000000.0,2.445276e+08,1990-05-25,Family,118.0,7.4,369652.0,"Learning about the death of Doc Brown in 1885,..."
45,46,Teenage Mutant Ninja Turtles II,PG,25000000.0,7.860000e+07,1991-03-22,Action,88.0,8.0,397467.0,The Turtles and the Shredder battle once again...
46,47,Beauty and the Beast,PG,25000000.0,3.773506e+08,1991-11-13,Animation,84.0,8.0,397467.0,A prince cursed to spend his days as a hideous...
49,50,Star Trek VI: The Undiscovered Country,PG,27000000.0,9.690000e+07,1991-12-05,Science Fiction,113.0,7.2,66086.0,"On the eve of retirement, Kirk and McCoy are c..."
72,73,A League of Their Own,PG,40000000.0,1.074588e+08,1992-07-01,Comedy,128.0,7.2,85932.0,Two sisters join the first female professional...
80,81,Groundhog Day,PG,14600000.0,7.090697e+07,1993-02-11,Comedy,101.0,8.0,549538.0,A weatherman finds himself inexplicably living...
106,107,Star Trek: Generations,PG,38000000.0,1.200000e+08,1994-11-17,Science Fiction,118.0,8.5,869127.0,With the help of long presumed dead Captain Ki...
126,127,Mr. Holland's Opus,PG,31000000.0,1.062700e+08,1995-12-29,Family,137.0,7.3,33906.0,A frustrated composer finds fulfillment as a h...
130,131,Apollo 13,PG,52000000.0,3.552379e+08,1995-06-30,Drama,140.0,7.6,250975.0,NASA must devise a strategy to return Apollo 1...
174,175,Contact,PG,90000000.0,1.711203e+08,1997-07-11,Science Fiction,150.0,7.4,239569.0,"Dr. Ellie Arroway (Jodie Foster), after years ..."
185,186,The Truman Show,PG,60000000.0,2.641182e+08,1998-06-04,Comedy,103.0,8.1,859224.0,An insurance salesman discovers his whole life...
188,189,The Prince of Egypt,PG,70000000.0,2.186132e+08,1998-12-15,Animation,99.0,7.1,110340.0,An Egyptian prince learns of his identity as a...
215,216,Tarzan,PG,150000000.0,4.480000e+08,1999-06-18,Animation,88.0,7.3,187724.0,A man raised by gorillas must decide where he ...
220,221,Remember the Titans,PG,30000000.0,1.367067e+08,2000-09-29,Drama,113.0,7.8,186997.0,The true story of a newly appointed African-Am...
241,242,Shrek,PG,60000000.0,4.844092e+08,2001-05-16,Animation,90.0,7.8,574978.0,A mean lord exiles fairytale creatures to the ...
255,256,Harry Potter and the Sorcerer's Stone,PG,125000000.0,9.751000e+08,2001-11-04,Fantasy,152.0,7.6,583224.0,An orphaned boy enrolls in a school of wizardr...
261,262,Ice Age,PG,59000000.0,3.832571e+08,2002-03-10,Animation,81.0,7.5,411963.0,"Set during the Ice Age, a sabertooth tiger, a ..."
270,271,Harry Potter and the Chamber of Secrets,PG,100000000.0,8.766885e+08,2002-11-13,Fantasy,161.0,7.4,505027.0,An ancient prophecy seems to be coming true wh...
304,305,The Incredibles,PG,92000000.0,6.314421e+08,2004-11-05,Animation,115.0,8.0,617102.0,"A family of undercover superheroes, while tryi..."
309,310,Harry Potter and the Prisoner of Azkaban,PG,130000000.0,7.898046e+08,2004-05-31,Fantasy,141.0,7.9,501648.0,Its Harrys third year at Hogwarts; not only do...
311,312,Shrek 2,PG,150000000.0,9.198388e+08,2004-05-19,Animation,93.0,7.2,391295.0,Princess Fionas parents invite her and Shrek t...
385,386,Kung Fu Panda,PG,130000000.0,6.317446e+08,2008-06-04,Animation,90.0,7.5,390478.0,The Dragon Warrior has to clash against the sa...
410,411,Monsters vs Aliens,PG,175000000.0,3.815099e+08,2009-03-19,Animation,94.0,7.7,374981.0,NaN
411,412,Up,PG,175000000.0,7.350991e+08,2009-05-13,Animation,96.0,8.2,867393.0,Seventy-eight year old Carl Fredricksen travel...
415,416,Harry Potter and the Half-Blood Prince,PG,250000000.0,9.339592e+08,2009-07-07,Fantasy,153.0,7.6,429384.0,As Harry Potter begins his sixth year at Hogwa...
420,421,Despicable Me,PG,69000000.0,5.435140e+08,2010-07-08,Animation,95.0,7.6,473121.0,When a criminal mastermind uses a trio of orph...
425,426,Megamind,PG,130000000.0,3.218872e+08,2010-10-28,Animation,95.0,7.2,212563.0,The supervillain Megamind finally defeats his ...
428,429,How to Train Your Dragon,PG,165000000.0,4.948788e+08,2010-03-05,Animation,98.0,8.1,624128.0,A hapless young Viking who aspires to hunt dra...
435,436,Tangled,PG,260000000.0,5.917949e+08,2010-11-24,Animation,100.0,7.7,374981.0,The magically long-haired Rapunzel has spent h...
447,448,Puss in Boots: The Three Diablos,PG,130000000.0,5.550000e+08,2011-12-08,Animation,130.0,7.8,727724.0,NaN
451,452,Kung Fu Panda 2,PG,150000000.0,6.656923e+08,2011-05-25,Animation,91.0,7.2,234612.0,Po and his friends fight to stop a peacock vil...
461,462,Hotel Transylvania,PG,85000000.0,3.583756e+08,2012-09-20,Animation,91.0,7.1,208916.0,"Dracula, who operates a high-end resort away f..."
466,467,Wreck-It Ralph,PG,165000000.0,4.712229e+08,2012-11-01,Animation,108.0,7.7,354202.0,A video game villain wants to be a hero and se...
468,469,Brave,PG,185000000.0,5.389832e+08,2012-06-21,Animation,93.0,7.1,346490.0,"Determined to make her own path in life, Princ..."
480,481,Despicable Me 2,PG,76000000.0,9.707619e+08,2013-06-25,Animation,98.0,7.4,350582.0,"When Gru, the worlds most super-bad turned sup..."
484,485,The Croods,PG,135000000.0,5.851789e+08,2013-03-20,Animation,98.0,7.2,180043.0,"After their cave is destroyed, a caveman famil..."
485,486,Frozen,PG,150000000.0,1.274219e+09,2013-11-27,Animation,102.0,7.5,527284.0,When the newly-crowned Queen Elsa accidentally...
498,499,The Lego Movie,PG,60000000.0,4.691607e+08,2014-02-06,Animation,100.0,7.8,309295.0,"An ordinary LEGO construction worker, thought ..."
503,504,How to Train Your Dragon 2,PG,145000000.0,6.091230e+08,2014-06-12,Animation,102.0,7.8,285394.0,When Hiccup and Toothless discover an ice cave...
505,506,Big Hero 6,PG,165000000.0,6.521054e+08,2014-10-24,Animation,102.0,7.8,380953.0,The special bond that develops between plus-si...

In [149]:
# 3.show the count of Animation movies with more than 7 in Rating (use the shape() method)
df[(df['Genre'] == 'Animation') & (df["Rating"] > 7)].shape

(39, 11)

In [150]:
# 4.show the top 5 movies based on Budget

df.sort_values("Budget", ascending=False).head(5)

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary
594,595,Avengers: Infinity War,PG-13,400000000.0,2.048000e+09,2018-04-23,Action,149.0,NaN,NaN,NaN
454,455,Pirates of the Caribbean: On Stranger Tides,PG-13,380000000.0,1.045714e+09,2011-05-14,Action,136.0,6.6,455211.0,Jack Sparrow and Barbossa embark on a quest to...
614,615,Avengers: Endgame,PG-13,356000000.0,2.796000e+09,2019-04-22,Action,181.0,NaN,NaN,NaN
574,575,Star Wars: The Last Jedi,PG-13,317000000.0,1.333000e+09,2019-12-09,Science Fiction,152.0,NaN,NaN,NaN
375,376,Pirates of the Caribbean: At World's End,PG-13,300000000.0,9.610000e+08,2007-05-19,Adventure,169.0,7.1,565402.0,"Captain Barbossa, Will Turner and Elizabeth Sw..."

In [151]:
# 5.show the top 5 Comedy movies by Rating

df[df['Genre'] == "Comedy"]
df[df['Genre'] == "Comedy"].sort_values("Rating", ascending=False).head(5)

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary
111,112,Forrest Gump,PG-13,55000000.0,677945399.0,1994-07-06,Comedy,142.0,8.8,1657851.0,"The presidencies of Kennedy and Johnson, the e..."
185,186,The Truman Show,PG,60000000.0,264118201.0,1998-06-04,Comedy,103.0,8.1,859224.0,An insurance salesman discovers his whole life...
80,81,Groundhog Day,PG,14600000.0,70906973.0,1993-02-11,Comedy,101.0,8.0,549538.0,A weatherman finds himself inexplicably living...
254,255,"Monsters, Inc.",G,115000000.0,562816256.0,2001-11-01,Comedy,92.0,8.0,758349.0,"In order to power the city, monsters have to s..."
316,317,The 40 Year Old Virgin,R,26000000.0,109449237.0,2005-08-11,Comedy,116.0,7.7,500448.0,"Goaded by his buddies, a nerdy guy who's never..."

In [152]:
# 6.top 5 movie names by Rating

df.sort_values("Rating", ascending=False).head(5)

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary
393,394,The Dark Knight,PG-13,185000000.0,1.004558e+09,2008-07-16,Action,152.0,9.0,2127228.0,When the menace known as the Joker wreaks havo...
98,99,Jurassic Park III,PG-13,93000000.0,3.688000e+08,2001-07-16,Thriller,92.0,8.9,1690474.0,A decidedly odd couple with ulterior motives ...
287,288,The Lord of the Rings: The Return of the King,PG-13,94000000.0,1.118889e+09,2003-12-01,Fantasy,201.0,8.9,1529953.0,Gandalf and Aragorn lead the World of Men agai...
99,100,Pulp Fiction,R,8000000.0,2.139288e+08,1994-09-10,Thriller,154.0,8.9,1690474.0,"The lives of two mob hitmen, a boxer, a gangst..."
83,84,Schindler's List,R,22000000.0,3.213656e+08,1993-11-29,History,195.0,8.9,1117322.0,"In German-occupied Poland during World War II,..."

In [212]:
# 7.top 3 high Gross Romance movies released after 1999 (typecast it to datetime)

df['Release Date'] = pd.to_datetime(df['Release Date'])
Movie_release = df[(df["Genre"] == "Romance") & (df['Release Date'].dt.year > 1999) ].head(3)
Movie_release
# df.sort_values("Gross").head(5)

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary
217,218,"Crouching Tiger, Hidden Dragon",PG-13,17000000.0,213525736.0,2000-10-01,Romance,120.0,7.8,242878.0,A young Chinese warrior steals a sword from a ...
239,240,The Princess Diaries,G,37000000.0,165335153.0,2001-08-03,Romance,115.0,6.3,118754.0,Mia Thermopolis has just found out that she is...
258,259,Sweet Home Alabama,PG-13,30000000.0,180622424.0,2002-09-26,Romance,108.0,6.2,96978.0,A young woman whos reinvented herself as a New...

In [153]:
# 8.how many Genres are present in the dataframe? (use value_counts() method which applies to Series, not Dataframe)
Genre_series  = df['Genre'].explode()
Genre_series.value_counts()

Genre
Action             110
Comedy              99
Animation           87
Drama               66
Thriller            41
Science Fiction     37
Adventure           30
Family              29
Romance             28
Fantasy             27
Crime               17
Horror              14
Mystery             11
War                  9
Western              6
History              4
Name: count, dtype: int64

In [ ]:
# 9.top 5 most expensive movies released after 1999 (measured by Budget)
# df[df["Release Date"], datetime (1999-12-31, %y-%m-%d)]
# df.sort_values("Budget",ascending = False).head(5)
df['Release Date'] = pd.to_datetime(df['Release Date'])

df[df["Budget"] & (df['Release Date'].dt.year > 1999)]


# df_result = df.sort_values('Budget',ascending=False).head(5)
# df_result
# df[df["Budget"] & (df['Release Date'].dt.year > 1999)] 
# df.sort_values('Budget',ascending = False).head(5)

In [164]:
# 10.most & least frequent MPAA Rating in the dataset in terms of occurrences
mpaa_rating_counts = df['MPAA Rating'].value_counts()


print("Most freq MPAA Rating :", mpaa_rating_counts.max())
print("Less freq MPAA Rating :",mpaa_rating_counts.min())
mpaa_rating_counts
# mpaa_rating_counts.iloc[0,0]

Most freq MPAA Rating : 285
Less freq MPAA Rating : 27

MPAA Rating
PG-13    285
PG       161
R        142
G         27
Name: count, dtype: int64

In [ ]:
# 11.most & least expensive Genre (take an average of all Budget measures grouped by Genre - use the groupBy() method)

Budget_avg_Genre = df.groupby('Genre')["Budget"].mean()  # try mediam & mode
Budget_avg_Genre

Genre
Action             1.441682e+08
Adventure          1.338333e+08
Animation          1.158793e+08
Comedy             4.957727e+07
Crime              5.658824e+07
Drama              5.592576e+07
Family             6.268966e+07
Fantasy            1.612111e+08
History            5.550000e+07
Horror             3.700429e+07
Mystery            1.035455e+08
Romance            4.540020e+07
Science Fiction    1.267838e+08
Thriller           8.658537e+07
War                9.075556e+07
Western            7.983333e+07
Name: Budget, dtype: float64

In [ ]:
# 12.which Genre is favoured the most?
most_rating = df.groupby('Genre')['Rating'].mean()  #try .value_counts()
most_rating 
#.head(1)

Genre
Action             7.023684
Adventure          6.665385
Animation          7.190476
Comedy             6.617021
Crime              6.875000
Drama              7.246429
Family             6.089286
Fantasy            7.436364
History            7.625000
Horror             6.644444
Mystery            6.820000
Romance            6.361538
Science Fiction    7.200000
Thriller           7.014706
War                7.412500
Western            7.420000
Name: Rating, dtype: float64